services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CapstoneProject
      POSTGRES_DB: college_marketplace_dev
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend
    ports:
      - "5173:80"

volumes:
  db_data:
